### ISSUE TITLE
The issue is this repo

### ISSUE THREAD

**Issue by ghost** [crrapi/aioprint#2]
Why

**Comment by Fogapod** [comment]
Any updates on this? Works for me in latest version, can probably be closed.

**Comment by crrapi** [comment]
Agreed, this appears to be functional now.

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
It is not fine

**Comment by ghost** [comment]
THIS REPO HAVE BEEN HACKED BY HOLY SPIRIT OF MONOX. YOUR CHEESE ARE NOW BELONG TO MY.
